---
title: Gravity Simulator
hero_image: images/banner.png
description: Learn about the effects of gravity and how to simulate them in Scratch
original_url: https://raspberrypi.org/learning/gravity-simulator
theme: blue
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: space
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Create your backdrop
- title: Add an astronaut
- title: Set the gravitational pull
- title: Landing on the ground
- title: What goes up must come down
- title: Gravity on other planets
- title: What next?