---
title: Gravity Simulator
hero_image: images/banner.png
description: Learn about the effects of gravity and how to simulate them in Scratch
original_url: https://raspberrypi.org/learning/gravity-simulator
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Simulate the effects of gravity on Mooncake
- title: Set the stage with a space theme
- title: Create variables to store data
- title: Setting the start position
- title: The simulation loop
- title: Landing on the ground
- title: What goes up must come down
- title: Simulate gravity on other planets
- title: What next?

